'use client';

import { ChangeEvent, CSSProperties, useEffect, useMemo, useRef, useState } from 'react';
import {
  AppSnapshot, DEFAULT_QUESTIONS, DEFAULT_SETTINGS, InterviewReport, LEARNING_ROUTES, Progress, Question, Rating,
  ReviewRecord, RATING_LABELS, Settings, createId, createSnapshot, dueQuestions, fillerCount, localDateKey,
  mergeBuiltInQuestions, normalizeQuestion, parseImportedCards, relativeReviewTime, reviewStreak, safeParse, scheduleReview, weakCauses,
} from '../lib/model';

type View='study'|'library'|'plan'|'practice'|'history'|'stats'|'settings';
type Evaluation={score:number;verdict:string;summary:string;hitPoints:string[];missedPoints:string[];suggestion:string;source:'ai'|'local';model?:string};
type Draft=Omit<Question,'keyPoints'|'tags'|'prerequisites'> & {keyPoints:string;tags:string;prerequisites:string};
type Account={authenticated:boolean;displayName?:string;email?:string;provider?:'chatgpt'|'proxy'|'cloudflare-access'|'development'};
type AuthOption={id:'local'|'chatgpt'|'github'|'google'|'email'|'proxy';label:string;description:string;available:boolean;href?:string};
type InterviewSession={role:string;questionIds:string[];index:number;scores:number[];startedAt:string;answer:string;evaluation:Evaluation|null};

const navItems:{id:View;label:string;icon:string}[]=[
  {id:'study',label:'今日复习',icon:'◎'},{id:'library',label:'知识题库',icon:'▦'},{id:'plan',label:'学习路线',icon:'⌁'},
  {id:'practice',label:'模拟面试',icon:'◉'},{id:'history',label:'回答历史',icon:'≋'},{id:'stats',label:'学习数据',icon:'↗'},{id:'settings',label:'设置',icon:'◇'},
];
const normalizedDefaults=DEFAULT_QUESTIONS.map(normalizeQuestion);
const emptyDraft=():Draft=>({id:'',category:'数据库',title:'',hint:'',keyPoints:'',reference:'',difficulty:1,strength:30,tags:'',favorite:false,routeIds:[],prerequisites:'',source:'手动'});
function isSnapshot(value:unknown):value is AppSnapshot {const item=value as AppSnapshot;return Boolean(item&&Array.isArray(item.questions)&&item.progress&&Array.isArray(item.history));}

export default function Home(){
  const [view,setView]=useState<View>('study'); const [questions,setQuestions]=useState<Question[]>(normalizedDefaults); const [progress,setProgress]=useState<Progress>({}); const [history,setHistory]=useState<ReviewRecord[]>([]);
  const [settings,setSettings]=useState<Settings>(DEFAULT_SETTINGS); const [interviewReports,setInterviewReports]=useState<InterviewReport[]>([]); const [hydrated,setHydrated]=useState(false);
  const [account,setAccount]=useState<Account>({authenticated:false}); const [authOptions,setAuthOptions]=useState<AuthOption[]>([]); const [cloudStatus,setCloudStatus]=useState<'local'|'loading'|'synced'|'saving'|'offline'|'conflict'>('loading');
  const cloudReady=useRef(false); const remoteVersion=useRef(0); const syncTimer=useRef<number|undefined>(undefined);
  const [currentId,setCurrentId]=useState<string|null>(null); const [manualReview,setManualReview]=useState(false); const [sessionDone,setSessionDone]=useState(false);
  const [answer,setAnswer]=useState(''); const [evaluation,setEvaluation]=useState<Evaluation|null>(null); const [followup,setFollowup]=useState(''); const [loading,setLoading]=useState(false);
  const [voiceState,setVoiceState]=useState<'idle'|'recording'|'transcribing'>('idle'); const recorder=useRef<MediaRecorder|null>(null); const recordingStarted=useRef(0); const [answerDuration,setAnswerDuration]=useState(0);
  const [search,setSearch]=useState(''); const [filter,setFilter]=useState('全部'); const [tagFilter,setTagFilter]=useState('全部'); const [favoritesOnly,setFavoritesOnly]=useState(false);
  const [toast,setToast]=useState(''); const [showReference,setShowReference]=useState(false); const [editorOpen,setEditorOpen]=useState(false); const [draft,setDraft]=useState<Draft>(emptyDraft());
  const [generatorOpen,setGeneratorOpen]=useState(false); const [sourceText,setSourceText]=useState(''); const [generated,setGenerated]=useState<Question[]>([]); const [aiMode,setAiMode]=useState<'loading'|'ai'|'local'>('loading'); const [aiUsage,setAiUsage]=useState(0);
  const [historyQuestion,setHistoryQuestion]=useState('全部'); const [interview,setInterview]=useState<InterviewSession|null>(null); const [practiceCount,setPracticeCount]=useState(5);

  function applySnapshot(snapshot:AppSnapshot){const needsBankUpgrade=(snapshot as {version?:number}).version!==3;setQuestions(needsBankUpgrade?mergeBuiltInQuestions(snapshot.questions):snapshot.questions.map(normalizeQuestion));setProgress(snapshot.progress||{});setHistory(snapshot.history||[]);setSettings({...DEFAULT_SETTINGS,...snapshot.settings});setInterviewReports(snapshot.interviewReports||[]);}
  useEffect(()=>{
    const modern=safeParse<AppSnapshot|null>(localStorage.getItem('yihe-snapshot'),null); const legacy=createSnapshot(safeParse<Question[]>(localStorage.getItem('yihe-questions'),normalizedDefaults),safeParse<Progress>(localStorage.getItem('yihe-progress'),{}),safeParse<ReviewRecord[]>(localStorage.getItem('yihe-history'),[]),DEFAULT_SETTINGS,[]);
    const hydrateTimer=window.setTimeout(()=>{applySnapshot(isSnapshot(modern)?modern:legacy);setHydrated(true);},0);
    fetch('/api/sync').then(async response=>({response,data:await response.json() as {authenticated?:boolean;user?:Account;authOptions?:AuthOption[];state?:unknown;version?:number;cloudUnavailable?:boolean}})).then(({response,data})=>{setAuthOptions(data.authOptions||[]);if(response.ok&&data.authenticated){setAccount({authenticated:true,...data.user});remoteVersion.current=data.version||0;if(isSnapshot(data.state))applySnapshot(data.state);cloudReady.current=true;setCloudStatus(data.cloudUnavailable?'offline':'synced');if(!data.state&&!data.cloudUnavailable)setSettings(old=>({...old}));}else setCloudStatus('local');}).catch(()=>setCloudStatus('local'));
    fetch('/api/evaluate').then(r=>r.json()).then(raw=>{const data=raw as {mode?:string;usage?:number};setAiMode(data.mode==='ai'?'ai':'local');setAiUsage(data.usage||0);}).catch(()=>setAiMode('local'));
    if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js').catch(()=>undefined);
    return()=>window.clearTimeout(hydrateTimer);
  },[]);
  useEffect(()=>{if(!hydrated)return;const snapshot=createSnapshot(questions,progress,history,settings,interviewReports);localStorage.setItem('yihe-snapshot',JSON.stringify(snapshot));if(!cloudReady.current)return;window.clearTimeout(syncTimer.current);setCloudStatus('saving');syncTimer.current=window.setTimeout(async()=>{try{const response=await fetch('/api/sync',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:snapshot,baseVersion:remoteVersion.current})});const data=await response.json() as {version?:number;state?:unknown};if(response.status===409&&isSnapshot(data.state)){remoteVersion.current=data.version||remoteVersion.current;applySnapshot(mergeSnapshots(snapshot,data.state));setCloudStatus('conflict');return;}if(!response.ok)throw new Error('sync');remoteVersion.current=data.version||remoteVersion.current;setCloudStatus('synced');}catch{setCloudStatus('offline');}},1200);return()=>window.clearTimeout(syncTimer.current);},[hydrated,questions,progress,history,settings,interviewReports]);

  const route=LEARNING_ROUTES.find(item=>item.id===settings.selectedRoute)||LEARNING_ROUTES[0]; const routedQuestions=route.categories.length?questions.filter(q=>route.categories.includes(q.category)||(q.routeIds||[]).includes(route.id)):questions;
  const dueAll=useMemo(()=>dueQuestions(routedQuestions,progress),[routedQuestions,progress]); const dailyQueue=dueAll.slice(0,settings.dailyGoal); const question=questions.find(item=>item.id===currentId)??(!sessionDone?dailyQueue[0]:null)??null;
  useEffect(()=>{if(!hydrated||!settings.notifications||Notification.permission!=='granted')return;const check=()=>{const now=new Date();const [hour,minute]=settings.reminderTime.split(':').map(Number);const key=`yihe-notified-${localDateKey(now)}`;if(now.getHours()*60+now.getMinutes()>=hour*60+minute&&dueAll.length&&localStorage.getItem(key)!=='1'){new Notification('忆核 · 今日复习',{body:`还有 ${dueAll.length} 个知识点等待巩固。`,icon:'/icon.svg'});localStorage.setItem(key,'1');}};check();const id=window.setInterval(check,60000);return()=>window.clearInterval(id);},[hydrated,settings.notifications,settings.reminderTime,dueAll.length]);
  const categories=useMemo(()=>['全部',...new Set(questions.map(q=>q.category))],[questions]); const tags=useMemo(()=>['全部',...new Set(questions.flatMap(q=>q.tags||[]))],[questions]);
  const filteredQuestions=questions.filter(q=>(filter==='全部'||q.category===filter)&&(tagFilter==='全部'||q.tags?.includes(tagFilter))&&(!favoritesOnly||q.favorite)&&`${q.title}${q.hint}${q.keyPoints.join('')}${q.tags?.join('')}`.toLowerCase().includes(search.toLowerCase()));
  const todayKey=hydrated?localDateKey(new Date()):''; const todayHistory=history.filter(item=>localDateKey(new Date(item.reviewedAt))===todayKey); const strengths=questions.map(q=>progress[q.id]?.strength??q.strength); const memoryHealth=strengths.length?Math.round(strengths.reduce((a,b)=>a+b,0)/strengths.length):0;
  const mastered=questions.filter(q=>(progress[q.id]?.strength??q.strength)>=70).length; const streak=reviewStreak(history); const avgScore=history.length?Math.round(history.reduce((sum,item)=>sum+item.score,0)/history.length):0; const dateLabel=hydrated?new Intl.DateTimeFormat('zh-CN',{month:'short',day:'numeric',weekday:'short'}).format(new Date()):'今天';
  const chart=Array.from({length:14},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(13-index));const key=localDateKey(date);return{key,label:index%3===0?`${date.getMonth()+1}/${date.getDate()}`:'',value:history.filter(item=>localDateKey(new Date(item.reviewedAt))===key).length};}); const maxChart=Math.max(1,...chart.map(item=>item.value)); const weakQuestions=[...questions].sort((a,b)=>(progress[a.id]?.strength??a.strength)-(progress[b.id]?.strength??b.strength)).slice(0,4);
  const shownHistory=history.filter(item=>historyQuestion==='全部'||item.questionId===historyQuestion).slice().reverse(); const upcoming=questions.map(q=>({q,p:progress[q.id]})).filter(item=>item.p&&new Date(item.p.nextReview)>new Date()).sort((a,b)=>a.p.nextReview.localeCompare(b.p.nextReview)).slice(0,4); const weekDays=Array.from({length:7},(_,index)=>{const date=new Date();date.setDate(date.getDate()-(6-index));const key=localDateKey(date);return{label:['日','一','二','三','四','五','六'][date.getDay()],done:history.some(item=>localDateKey(new Date(item.reviewedAt))===key)};});

  function notify(message:string){setToast(message);window.setTimeout(()=>setToast(''),2800);} function resetAnswer(){setAnswer('');setEvaluation(null);setFollowup('');setShowReference(false);setAnswerDuration(0);}
  async function evaluateAnswer(target=question,text=answer){if(!target||!text.trim()||loading)return null;setLoading(true);try{const response=await fetch('/api/evaluate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:target.title,answer:text,keyPoints:target.keyPoints,reference:target.reference,model:settings.model,dailyLimit:settings.dailyAiLimit})});if(!response.ok)throw new Error('failed');const result=await response.json() as Evaluation;setAiUsage(value=>value+(result.source==='ai'?1:0));return result;}catch{return{score:60,verdict:'已记录回答',summary:'服务暂时不可用，请对照参考答案自评。',hitPoints:[],missedPoints:target.keyPoints,suggestion:'先分点列出概念，再补充作用或例子。',source:'local' as const};}finally{setLoading(false);}}
  async function submitAnswer(){const result=await evaluateAnswer();if(result)setEvaluation(result);} async function makeFollowup(){if(!question||!evaluation)return;setFollowup('正在生成追问…');try{const response=await fetch('/api/followup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:question.title,answer,missedPoints:evaluation.missedPoints,model:settings.model})});const data=await response.json() as {question?:string};setFollowup(data.question||'请再用一个实际场景解释你的结论。');}catch{setFollowup('请再用一个实际场景解释你的结论。');}}
  function rate(rating:Rating){if(!question||!evaluation)return;const nextProgress=scheduleReview(question,progress[question.id],rating,evaluation.score,new Date(),settings.targetRetention);const record:ReviewRecord={id:createId('review'),questionId:question.id,category:question.category,score:evaluation.score,rating,reviewedAt:new Date().toISOString(),answer,verdict:evaluation.verdict,summary:evaluation.summary,hitPoints:evaluation.hitPoints,missedPoints:evaluation.missedPoints,suggestion:evaluation.suggestion,source:evaluation.source,model:evaluation.model||settings.model,durationSeconds:answerDuration,fillerCount:fillerCount(answer)};const next={...progress,[question.id]:nextProgress};setProgress(next);setHistory(items=>[...items,record]);notify(`已安排 ${relativeReviewTime(nextProgress.nextReview)}复习`);resetAnswer();setManualReview(false);const remaining=dueQuestions(routedQuestions,next).slice(0,settings.dailyGoal).find(item=>item.id!==question.id);if(remaining)setCurrentId(remaining.id);else{setCurrentId(null);setSessionDone(true);}}

  async function startVoice(){if(voiceState==='recording'){recorder.current?.stop();setVoiceState('transcribing');return;}if(!navigator.mediaDevices?.getUserMedia){startBrowserSpeech();return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const chunks:BlobPart[]=[];const media=new MediaRecorder(stream);recorder.current=media;recordingStarted.current=new Date().getTime();media.ondataavailable=e=>chunks.push(e.data);media.onstop=async()=>{stream.getTracks().forEach(track=>track.stop());setAnswerDuration(Math.round((new Date().getTime()-recordingStarted.current)/1000));const form=new FormData();form.set('audio',new File(chunks,'answer.webm',{type:media.mimeType||'audio/webm'}));try{const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json() as {text?:string};if(data.text)setAnswer(old=>`${old}${old?' ':''}${data.text}`);else{startBrowserSpeech();notify('录音已保存，改用浏览器语音识别补充转写');}}catch{startBrowserSpeech();}finally{setVoiceState('idle');}};media.start();setVoiceState('recording');}catch{startBrowserSpeech();}}
  function startBrowserSpeech(){type R={lang:string;interimResults:boolean;start:()=>void;onresult:(e:{results:ArrayLike<{0:{transcript:string}}>})=>void;onend:()=>void;onerror:()=>void};type W=Window&{SpeechRecognition?:new()=>R;webkitSpeechRecognition?:new()=>R};const C=(window as W).SpeechRecognition||(window as W).webkitSpeechRecognition;if(!C){notify('当前浏览器暂不支持语音输入');setVoiceState('idle');return;}const recognition=new C();recognition.lang='zh-CN';recognition.interimResults=false;recordingStarted.current=new Date().getTime();recognition.onresult=e=>setAnswer(old=>`${old}${old?' ':''}${e.results[0][0].transcript}`);recognition.onend=()=>{setAnswerDuration(Math.round((new Date().getTime()-recordingStarted.current)/1000));setVoiceState('idle');};recognition.onerror=()=>{setVoiceState('idle');notify('没有识别到语音');};setVoiceState('recording');recognition.start();}

  function jumpToQuestion(id:string){setCurrentId(id);setManualReview(true);setSessionDone(false);resetAnswer();setView('study');} function openNew(){setDraft(emptyDraft());setEditorOpen(true);} function openEdit(q:Question){setDraft({...q,keyPoints:q.keyPoints.join('\n'),tags:(q.tags||[]).join('，'),prerequisites:(q.prerequisites||[]).join('，')});setEditorOpen(true);}
  function saveQuestion(){const keyPoints=draft.keyPoints.split('\n').map(v=>v.trim()).filter(Boolean);if(!draft.title.trim()||!draft.reference.trim()||!keyPoints.length){notify('请填写题目、评分要点和参考答案');return;}const item=normalizeQuestion({...draft,id:draft.id||createId(),category:draft.category.trim()||'待整理',title:draft.title.trim(),hint:draft.hint.trim(),keyPoints,reference:draft.reference.trim(),tags:draft.tags.split(/[，,]/).map(v=>v.trim()).filter(Boolean),prerequisites:draft.prerequisites.split(/[，,]/).map(v=>v.trim()).filter(Boolean)});setQuestions(items=>draft.id?items.map(old=>old.id===draft.id?item:old):[item,...items]);setEditorOpen(false);notify(draft.id?'知识点已更新':'知识点已添加');}
  function deleteQuestion(q:Question){if(!confirm(`确定删除“${q.title}”吗？`))return;setQuestions(items=>items.filter(item=>item.id!==q.id));setProgress(old=>{const next={...old};delete next[q.id];return next;});setHistory(items=>items.filter(item=>item.questionId!==q.id));notify('知识点已删除');} function toggleFavorite(q:Question){setQuestions(items=>items.map(item=>item.id===q.id?{...item,favorite:!item.favorite}:item));}
  async function importData(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;try{const text=await file.text();if(file.name.endsWith('.json')){const data=JSON.parse(text) as unknown;if(isSnapshot(data)){applySnapshot(data);notify('完整学习数据已导入');return;}if(Array.isArray(data)){const cards=(data as Question[]).map(normalizeQuestion);setQuestions(items=>[...cards,...items]);notify(`已导入 ${cards.length} 张卡片`);return;}}const cards=parseImportedCards(text,file.name);if(!cards.length)throw new Error('empty');setQuestions(items=>[...cards,...items]);notify(`已导入 ${cards.length} 张卡片`);}catch{notify('导入失败，请检查文件格式');}}
  function exportData(){download(new Blob([JSON.stringify(createSnapshot(questions,progress,history,settings,interviewReports),null,2)],{type:'application/json'}),`忆核完整备份-${todayKey}.json`);notify('完整备份已导出');} function sharePack(){download(new Blob([JSON.stringify(filteredQuestions,null,2)],{type:'application/json'}),`忆核知识包-${filter}-${todayKey}.json`);notify(`已导出 ${filteredQuestions.length} 张可分享卡片`);}
  async function generateCards(){if(sourceText.trim().length<20){notify('请粘贴至少 20 个字的材料');return;}setLoading(true);try{const response=await fetch('/api/generate-cards',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:sourceText,count:8,model:settings.model})});const data=await response.json() as {cards?:Partial<Question>[];source?:string};const cards=(data.cards||[]).map((card,index)=>normalizeQuestion({id:createId('ai'),category:card.category||'待整理',title:card.title||`知识点 ${index+1}`,hint:card.hint||'',keyPoints:card.keyPoints||[],reference:card.reference||'',difficulty:card.difficulty||1,strength:30,tags:card.tags||['AI生成'],source:data.source==='ai'?'AI 制卡':'本地制卡'}));setGenerated(cards);notify(`已生成 ${cards.length} 张卡片`);}catch{notify('制卡失败');}finally{setLoading(false);}} function addGenerated(){setQuestions(items=>[...generated,...items]);setGenerated([]);setSourceText('');setGeneratorOpen(false);notify('卡片已加入题库');}
  async function enableReminder(){if(!('Notification'in window)){notify('当前浏览器不支持通知');return;}const permission=await Notification.requestPermission();setSettings(old=>({...old,notifications:permission==='granted'}));notify(permission==='granted'?'每日提醒已开启':'未获得通知权限');} function exportCalendar(){const [hour,minute]=settings.reminderTime.split(':').map(Number);const start=new Date();start.setHours(hour,minute,0,0);const stamp=start.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');download(new Blob([`BEGIN:VCALENDAR\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nUID:yihe-daily-review\r\nDTSTART:${stamp}\r\nDURATION:PT20M\r\nRRULE:FREQ=DAILY\r\nSUMMARY:忆核 · 每日知识复习\r\nEND:VEVENT\r\nEND:VCALENDAR`],{type:'text/calendar'}),'忆核每日复习.ics');}
  function resetAll(){if(!confirm('确定恢复默认题库并清空全部记录吗？建议先导出备份。'))return;setQuestions(normalizedDefaults);setProgress({});setHistory([]);setSettings(DEFAULT_SETTINGS);setInterviewReports([]);notify('已恢复默认数据');}
  function startInterview(){const pool=[...routedQuestions].sort(()=>Math.random()-.5).slice(0,Math.min(practiceCount,routedQuestions.length));if(!pool.length){notify('当前路线没有题目');return;}setInterview({role:route.name,questionIds:pool.map(q=>q.id),index:0,scores:[],startedAt:new Date().toISOString(),answer:'',evaluation:null});} async function submitInterview(){if(!interview)return;const q=questions.find(item=>item.id===interview.questionIds[interview.index]);const result=await evaluateAnswer(q,interview.answer);if(result)setInterview(old=>old?{...old,evaluation:result}:old);} function nextInterview(){if(!interview?.evaluation)return;const scores=[...interview.scores,interview.evaluation.score];if(interview.index+1<interview.questionIds.length){setInterview({...interview,index:interview.index+1,scores,answer:'',evaluation:null});return;}const completedAt=new Date().toISOString();setInterviewReports(items=>[{id:createId('interview'),role:interview.role,questionIds:interview.questionIds,scores,startedAt:interview.startedAt,completedAt,durationSeconds:Math.round((Date.now()-new Date(interview.startedAt).getTime())/1000)},...items]);setInterview(null);notify(`模拟面试完成，平均 ${Math.round(scores.reduce((a,b)=>a+b,0)/scores.length)} 分`);}

  const titles:Record<View,string>={study:'用自己的语言，讲清今天的知识。',library:'把知识拆小，才能记得更久。',plan:'沿着路线学习，也看清知识关系。',practice:'像真实面试一样组织答案。',history:'每次回答都留下证据。',stats:'看见积累，也定位反复遗漏。',settings:'让节奏、AI 和数据由你掌控。'};
  return <main className="app-shell"><a className="skip-link" href="#main-content">跳到主要内容</a>{toast&&<div className="toast" role="status">✓ {toast}</div>}<aside className="sidebar"><button className="brand" onClick={()=>setView('study')}><span className="brand-mark">忆</span><span>忆核</span></button><nav className="nav-list" aria-label="主导航">{navItems.map(item=><button key={item.id} onClick={()=>setView(item.id)} className={`nav-item ${view===item.id?'active':''}`}><span>{item.icon}</span>{item.label}{item.id==='study'&&<b>{dueAll.length}</b>}</button>)}</nav><div className="sidebar-bottom"><p>近 7 天</p><strong>学习了 {weekDays.filter(day=>day.done).length} 天</strong><div className="week-dots">{weekDays.map((day,index)=><i key={index} className={day.done?'done':''}>{day.label}</i>)}</div></div></aside><section className="workspace" id="main-content"><header className="topbar"><div><span className="eyebrow">{dateLabel} · {route.name}</span><h1>{titles[view]}</h1></div><div className="topbar-actions"><span className={`sync-badge ${cloudStatus}`}>{cloudStatus==='synced'?'☁ 已同步':cloudStatus==='saving'?'↻ 保存中':cloudStatus==='offline'?'离线缓存':cloudStatus==='conflict'?'已合并冲突':'本机保存'}</span><div className="streak"><span>↗</span><div><b>{streak} 天</b><small>{account.authenticated?account.displayName:'连续学习'}</small></div></div></div></header>
  {view==='study'&&(question?<StudyView question={question} progress={progress} evaluation={evaluation} answer={answer} setAnswer={setAnswer} submitAnswer={submitAnswer} loading={loading} voiceState={voiceState} startVoice={startVoice} showReference={showReference} setShowReference={setShowReference} followup={followup} makeFollowup={makeFollowup} rate={rate} settings={settings} memoryHealth={memoryHealth} mastered={mastered} todayHistory={todayHistory.length} manualReview={manualReview} upcoming={upcoming} jump={jumpToQuestion}/>:<section className="session-complete"><div className="complete-orbit">✓</div><span className="section-label">SESSION COMPLETE</span><h2>{questions.length?'今日目标已完成':'题库还是空的'}</h2><p>{questions.length?`今天已完成 ${todayHistory.length} 次复习。到期任务会按 ${Math.round(settings.targetRetention*100)}% 目标记忆率再次出现。`:'添加第一个知识点，开始建立长期记忆系统。'}</p><div><button className="primary-action" onClick={()=>setView('library')}>{questions.length?'自由复习':'添加知识点'}</button></div></section>)}
  {view==='library'&&<LibraryView questions={filteredQuestions} allCount={questions.length} categories={categories} tags={tags} filter={filter} setFilter={setFilter} tagFilter={tagFilter} setTagFilter={setTagFilter} search={search} setSearch={setSearch} favoritesOnly={favoritesOnly} setFavoritesOnly={setFavoritesOnly} progress={progress} jump={jumpToQuestion} openEdit={openEdit} remove={deleteQuestion} favorite={toggleFavorite} openNew={openNew} openGenerator={()=>setGeneratorOpen(true)} importData={importData}/>} 
  {view==='plan'&&<PlanView questions={questions} progress={progress} selected={settings.selectedRoute} onSelect={id=>setSettings(old=>({...old,selectedRoute:id}))} jump={jumpToQuestion} history={history}/>} 
  {view==='practice'&&<PracticeView route={route} interview={interview} questions={questions} practiceCount={practiceCount} setPracticeCount={setPracticeCount} start={startInterview} setInterview={setInterview} submit={submitInterview} next={nextInterview} loading={loading} reports={interviewReports}/>} 
  {view==='history'&&<HistoryView questions={questions} records={shownHistory} selected={historyQuestion} setSelected={setHistoryQuestion} jump={jumpToQuestion}/>} 
  {view==='stats'&&<StatsView history={history} questions={questions} progress={progress} chart={chart} maxChart={maxChart} avgScore={avgScore} mastered={mastered} streak={streak} weak={weakQuestions} jump={jumpToQuestion}/>} 
  {view==='settings'&&<><AuthPanel account={account} options={authOptions} cloudStatus={cloudStatus}/><SettingsView settings={settings} setSettings={setSettings} account={account} cloudStatus={cloudStatus} aiMode={aiMode} aiUsage={aiUsage} enableReminder={enableReminder} exportCalendar={exportCalendar} exportData={exportData} importData={importData} sharePack={sharePack} resetAll={resetAll}/></>} </section>
  {editorOpen&&<Editor draft={draft} setDraft={setDraft} save={saveQuestion} close={()=>setEditorOpen(false)}/>} {generatorOpen&&<Generator text={sourceText} setText={setSourceText} cards={generated} generate={generateCards} add={addGenerated} loading={loading} close={()=>setGeneratorOpen(false)}/>}</main>;
}

function StudyView({question,progress,evaluation,answer,setAnswer,submitAnswer,loading,voiceState,startVoice,showReference,setShowReference,followup,makeFollowup,rate,settings,memoryHealth,mastered,todayHistory,manualReview,upcoming,jump}:{question:Question;progress:Progress;evaluation:Evaluation|null;answer:string;setAnswer:(v:string)=>void;submitAnswer:()=>void;loading:boolean;voiceState:string;startVoice:()=>void;showReference:boolean;setShowReference:(v:boolean)=>void;followup:string;makeFollowup:()=>void;rate:(r:Rating)=>void;settings:Settings;memoryHealth:number;mastered:number;todayHistory:number;manualReview:boolean;upcoming:{q:Question;p:Progress[string]}[];jump:(id:string)=>void}){
  const active=progress[question.id]?.strength??question.strength;
  return <div className="content-grid"><section className="study-area"><div className="session-head"><div><span className="section-label">TODAY&apos;S SESSION</span><h2>{manualReview?'自由复习':'今日复习'}</h2></div><div className="session-progress"><b>{String(Math.min(settings.dailyGoal,todayHistory+1)).padStart(2,'0')}</b><span>/ {settings.dailyGoal}</span></div></div><div className="progress-track"><i style={{width:`${Math.min(100,todayHistory/Math.max(1,settings.dailyGoal)*100)}%`}}/></div><article className="question-card"><div className="question-meta"><span className="topic-chip">{question.category}</span><span className="memory-chip"><i/> 记忆强度 {active}%</span>{question.favorite&&<span className="memory-chip">★ 已收藏</span>}</div><p className="question-kicker">KNOWLEDGE RECALL · {'◆'.repeat(question.difficulty)}{'◇'.repeat(3-question.difficulty)}</p><h3>{question.title}</h3><p className="hint">{question.hint||'请尽量完整地讲出概念、原理和适用场景。'}</p>
  {!evaluation?<div className="answer-box"><textarea value={answer} onChange={e=>setAnswer(e.target.value)} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter')submitAnswer();}} placeholder="用自己的话写下答案，不必追求标准表述……" autoFocus/><div className="answer-actions"><button className={`voice-button ${voiceState==='recording'?'listening':''}`} onClick={startVoice}><span className="record-dot">●</span><span>{voiceState==='recording'?'停止并转写':voiceState==='transcribing'?'正在转写…':'录音回答'}</span></button><small>{answer.length} 字 · 填充词 {fillerCount(answer)} 个 · ⌘ Enter</small><button className="submit-button" onClick={submitAnswer} disabled={!answer.trim()||loading}>{loading?'正在评估…':'提交评估'} <span>→</span></button></div></div>:
  <div className="evaluation-panel"><div className="evaluation-head"><div className="score-ring" style={{'--score':`${evaluation.score*3.6}deg`} as CSSProperties}><span><strong>{evaluation.score}</strong><small>/100</small></span></div><div><span className="section-label">{evaluation.source==='ai'?'AI FEEDBACK':'LOCAL FEEDBACK'}</span><h4>{evaluation.verdict}</h4><p>{evaluation.summary}</p></div></div><div className="point-columns"><div><b>✓ 已覆盖</b>{evaluation.hitPoints.length?evaluation.hitPoints.map(point=><span key={point}>{point}</span>):<span>继续补充核心概念</span>}</div><div><b>＋ 可补充</b>{evaluation.missedPoints.length?evaluation.missedPoints.slice(0,4).map(point=><span key={point}>{point}</span>):<span>核心要点已经覆盖完整</span>}</div></div><div className="ai-tip"><b>表达建议</b><p>{evaluation.suggestion}</p></div><div className="followup-box"><button onClick={makeFollowup}>◇ 让面试官追问</button>{followup&&<p>{followup}</p>}</div><button className="reference-toggle" onClick={()=>setShowReference(!showReference)}>{showReference?'收起参考答案':'查看参考答案'} <span>⌄</span></button>{showReference&&<p className="reference-answer">{question.reference}</p>}<div className="rating-row"><p>这道题你掌握得怎么样？<small>FSRS 按 {Math.round(settings.targetRetention*100)}% 目标记忆率安排</small></p>{(['again','hard','good','easy'] as Rating[]).map(r=>{const preview=scheduleReview(question,progress[question.id],r,evaluation.score,new Date(),settings.targetRetention);return <button key={r} className={r==='good'?'recommended':''} onClick={()=>rate(r)}><b>{RATING_LABELS[r].title}</b><span>{relativeReviewTime(preview.nextReview)}</span></button>;})}</div></div>}</article></section>
  <aside className="insights"><div className="memory-card"><div className="orbit"><span>{memoryHealth}<small>%</small></span></div><div><span className="section-label">MEMORY HEALTH</span><h3>{memoryHealth>=70?'记忆状态很好':memoryHealth>=45?'记忆状态良好':'正处于积累期'}</h3><p>{mastered} 个知识点已稳定掌握</p></div></div><div className="due-card"><div className="card-title"><span className="section-label">COMING UP</span></div><h3>接下来复习</h3>{upcoming.length?<ul>{upcoming.map((item,index)=><li key={item.q.id}><i className={`dot ${['purple','green','orange'][index%3]}`}/><button onClick={()=>jump(item.q.id)}><b>{item.q.title.slice(0,16)}…</b><span>{item.q.category} · {relativeReviewTime(item.p.nextReview)}</span></button><em>{item.p.strength}%</em></li>)}</ul>:<p className="empty-upcoming">完成一次复习后，这里会显示后续安排。</p>}</div><div className="quote-card"><span>“</span><p>真正的掌握，始于你能用自己的语言把它讲清楚。</p></div></aside></div>;
}

function PageHeading({label,title,text,children}:{label:string;title:string;text:string;children?:React.ReactNode}){return <div className="page-heading"><div><span className="section-label">{label}</span><h2>{title}</h2><p>{text}</p></div>{children}</div>}

function LibraryView({questions,allCount,categories,tags,filter,setFilter,tagFilter,setTagFilter,search,setSearch,favoritesOnly,setFavoritesOnly,progress,jump,openEdit,remove,favorite,openNew,openGenerator,importData}:{questions:Question[];allCount:number;categories:string[];tags:string[];filter:string;setFilter:(v:string)=>void;tagFilter:string;setTagFilter:(v:string)=>void;search:string;setSearch:(v:string)=>void;favoritesOnly:boolean;setFavoritesOnly:(v:boolean)=>void;progress:Progress;jump:(id:string)=>void;openEdit:(q:Question)=>void;remove:(q:Question)=>void;favorite:(q:Question)=>void;openNew:()=>void;openGenerator:()=>void;importData:(e:ChangeEvent<HTMLInputElement>)=>void}){
  return <section className="library-view"><PageHeading label="KNOWLEDGE BASE" title="知识题库" text={`${allCount} 个知识点 · ${tags.length-1} 个标签 · 支持 CSV / Markdown / JSON`}><div className="heading-actions"><button className="secondary-action" onClick={openGenerator}>◇ AI 制卡</button><label className="secondary-action file-label">↑ 批量导入<input type="file" accept=".json,.csv,.md,.markdown" onChange={importData}/></label><button className="primary-action" onClick={openNew}>＋ 添加</button></div></PageHeading><div className="library-toolbar"><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="搜索题目、标签或要点"/></label><div className="filter-tabs">{categories.map(item=><button key={item} className={filter===item?'active':''} onClick={()=>setFilter(item)}>{item}</button>)}</div><select value={tagFilter} onChange={e=>setTagFilter(e.target.value)}>{tags.map(tag=><option key={tag}>{tag}</option>)}</select><button className={favoritesOnly?'active-toggle':''} onClick={()=>setFavoritesOnly(!favoritesOnly)}>★ 收藏</button></div><div className="question-table"><div className="table-head"><span>知识点</span><span>难度</span><span>记忆强度</span><span>下次复习</span><span>操作</span></div>{questions.length?questions.map((q,index)=>{const item=progress[q.id];const strength=item?.strength??q.strength;return <div className="table-row" key={q.id}><div><button className={`favorite ${q.favorite?'on':''}`} onClick={()=>favorite(q)} aria-label="收藏">★</button><i className={`category-mark c${index%4}`}>{q.category.slice(0,1)}</i><span><b>{q.title}</b><small>{q.category} · {(q.tags||[]).join(' / ')||'未加标签'} · 已复习 {item?.reviews??0} 次</small></span></div><span className="difficulty">{'●'.repeat(q.difficulty)}{'○'.repeat(3-q.difficulty)}</span><div className="strength-bar"><i><em style={{width:`${strength}%`}}/></i><b>{strength}%</b></div><span className="next-date">{item?relativeReviewTime(item.nextReview):'现在'}</span><div className="table-actions"><button onClick={()=>jump(q.id)}>复习</button><button onClick={()=>openEdit(q)}>编辑</button><button className="danger" onClick={()=>remove(q)}>删除</button></div></div>}):<div className="table-empty">没有匹配的知识点</div>}</div></section>;
}

function PlanView({questions,progress,selected,onSelect,jump,history}:{questions:Question[];progress:Progress;selected:string;onSelect:(id:string)=>void;jump:(id:string)=>void;history:ReviewRecord[]}){
  const weak=[...questions].sort((a,b)=>(progress[a.id]?.strength??a.strength)-(progress[b.id]?.strength??b.strength)).slice(0,6);
  return <section className="plan-view"><PageHeading label="LEARNING ROUTES" title="学习路线与知识图谱" text="选择目标岗位路线，今日复习会自动聚焦相关知识。"/><div className="route-grid">{LEARNING_ROUTES.map(route=>{const cards=route.categories.length?questions.filter(q=>route.categories.includes(q.category)):questions;const done=cards.filter(q=>(progress[q.id]?.strength??q.strength)>=70).length;return <button key={route.id} className={selected===route.id?'selected':''} onClick={()=>onSelect(route.id)}><span>{selected===route.id?'当前路线':'选择路线'}</span><h3>{route.name}</h3><p>{route.description}</p><i><em style={{width:`${cards.length?done/cards.length*100:0}%`}}/></i><small>{done} / {cards.length} 稳定掌握</small></button>})}</div><div className="graph-layout"><article className="knowledge-graph"><span className="section-label">KNOWLEDGE GRAPH</span><h3>薄弱知识关系</h3><div className="graph-canvas">{weak.map((q,index)=><button key={q.id} style={{'--x':`${12+(index%3)*35}%`,'--y':`${18+Math.floor(index/3)*48}%`} as CSSProperties} onClick={()=>jump(q.id)}><b>{q.category}</b><span>{q.title.slice(0,12)}</span></button>)}</div></article><article className="cause-card"><span className="section-label">WEAKNESS DIAGNOSIS</span><h3>反复遗漏原因</h3>{weak.slice(0,3).map(q=><div key={q.id}><b>{q.title.slice(0,22)}…</b>{weakCauses(q,history).length?weakCauses(q,history).map(item=><span key={item.point}>{item.point.slice(0,28)} · {item.count} 次</span>):<span>尚无足够记录，先完成一次复习</span>}</div>)}</article></div></section>;
}

function PracticeView({route,interview,questions,practiceCount,setPracticeCount,start,setInterview,submit,next,loading,reports}:{route:(typeof LEARNING_ROUTES)[number];interview:InterviewSession|null;questions:Question[];practiceCount:number;setPracticeCount:(v:number)=>void;start:()=>void;setInterview:React.Dispatch<React.SetStateAction<InterviewSession|null>>;submit:()=>void;next:()=>void;loading:boolean;reports:InterviewReport[]}){
  if(interview){const q=questions.find(item=>item.id===interview.questionIds[interview.index]);if(!q)return null;return <section className="practice-view"><PageHeading label="MOCK INTERVIEW" title={`${interview.role} · 第 ${interview.index+1} / ${interview.questionIds.length} 题`} text="计时、随机抽题，回答后立即获得面试官反馈。"/><article className="interview-card"><span className="topic-chip">{q.category}</span><h2>{q.title}</h2><textarea value={interview.answer} onChange={e=>setInterview(old=>old?{...old,answer:e.target.value}:old)} placeholder="像正式面试一样组织答案……"/>{interview.evaluation&&<div className="interview-result"><strong>{interview.evaluation.score}</strong><div><b>{interview.evaluation.verdict}</b><p>{interview.evaluation.summary}</p></div></div>}<div><button className="secondary-action" onClick={()=>setInterview(null)}>退出</button>{interview.evaluation?<button className="primary-action" onClick={next}>{interview.index+1===interview.questionIds.length?'完成并生成报告':'下一题 →'}</button>:<button className="primary-action" onClick={submit} disabled={!interview.answer.trim()||loading}>{loading?'评估中…':'提交回答'}</button>}</div></article></section>}
  return <section className="practice-view"><PageHeading label="INTERVIEW LAB" title="模拟面试" text="从当前学习路线随机抽题，结束后生成能力报告。"/><div className="practice-grid"><article><span className="step-number">01</span><h3>{route.name}</h3><p>抽题范围：{route.categories.join('、')||'全部分类'}</p><label>题目数量 <input type="range" min="3" max="10" value={practiceCount} onChange={e=>setPracticeCount(Number(e.target.value))}/><b>{practiceCount} 题</b></label><button className="primary-action" onClick={start}>开始模拟面试 →</button></article><article><span className="step-number">02</span><h3>随机限时测验</h3><p>打乱题目顺序，不显示提示和参考答案，用于检验脱离熟悉顺序后的真实掌握。</p><button className="secondary-action" onClick={start}>开始随机测验</button></article><article><span className="step-number">03</span><h3>最近报告</h3>{reports.length?reports.slice(0,4).map(report=><div className="report-row" key={report.id}><b>{report.role}</b><span>{Math.round(report.scores.reduce((a,b)=>a+b,0)/report.scores.length)} 分 · {report.questionIds.length} 题 · {Math.round(report.durationSeconds/60)} 分钟</span></div>):<p>完成第一次模拟后，这里会显示得分、耗时和薄弱方向。</p>}</article></div></section>;
}

function HistoryView({questions,records,selected,setSelected,jump}:{questions:Question[];records:ReviewRecord[];selected:string;setSelected:(v:string)=>void;jump:(id:string)=>void}){
  const trend=records.slice().reverse();return <section className="history-view"><PageHeading label="ANSWER ARCHIVE" title="回答历史" text="保留原回答、AI 反馈、遗漏点与表达指标，可比较同一道题的多次尝试。"><select value={selected} onChange={e=>setSelected(e.target.value)}><option>全部</option>{questions.map(q=><option key={q.id} value={q.id}>{q.title.slice(0,32)}</option>)}</select></PageHeading>{selected!=='全部'&&trend.length>1&&<div className="comparison-strip">{trend.map((record,index)=><span key={record.id}><small>第 {index+1} 次</small><b>{record.score}</b><i style={{height:`${record.score}%`}}/></span>)}</div>}<div className="history-list">{records.length?records.map(record=>{const q=questions.find(item=>item.id===record.questionId);return <article key={record.id}><div className="history-head"><div><span className="topic-chip">{record.category}</span><h3>{q?.title||'已删除的知识点'}</h3><small>{new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(record.reviewedAt))} · {record.source==='ai'?'AI 评估':'本地评估'} · {record.durationSeconds||0} 秒</small></div><strong>{record.score}<small>/100</small></strong></div><div className="history-body"><div><b>当时的回答</b><p>{record.answer||'旧版本未保存原始回答'}</p></div><div><b>当时遗漏</b>{record.missedPoints?.length?record.missedPoints.map(point=><p key={point}>＋ {point}</p>):<p>核心要点覆盖完整</p>}</div></div><footer><span>填充词 {record.fillerCount??0} 个 · 自评「{RATING_LABELS[record.rating].title}」</span>{q&&<button onClick={()=>jump(q.id)}>再答一次 →</button>}</footer></article>}):<div className="table-empty">完成复习后，每次回答与反馈都会保存在这里。</div>}</div></section>;
}

function StatsView({history,questions,progress,chart,maxChart,avgScore,mastered,streak,weak,jump}:{history:ReviewRecord[];questions:Question[];progress:Progress;chart:{key:string;label:string;value:number}[];maxChart:number;avgScore:number;mastered:number;streak:number;weak:Question[];jump:(id:string)=>void}){
  const category=[...new Set(questions.map(q=>q.category))].map(name=>{const items=questions.filter(q=>q.category===name);return[name,Math.round(items.reduce((sum,q)=>sum+(progress[q.id]?.strength??q.strength),0)/items.length)] as const}).sort((a,b)=>b[1]-a[1]);
  return <section className="stats-view"><PageHeading label="LEARNING INSIGHTS" title="学习数据" text="活动、掌握度、表达习惯和反复遗漏都来自真实复习记录。"><span className="status-pill">近 14 天</span></PageHeading><div className="metric-grid"><article><span>累计复习</span><strong>{history.length}<small> 次</small></strong><em>持续输出比浏览更重要</em></article><article><span>平均得分</span><strong>{avgScore}<small> 分</small></strong><em>{history.length?'正在形成稳定表达':'等待第一次回答'}</em></article><article><span>稳定掌握</span><strong>{mastered}<small> / {questions.length}</small></strong><em>{questions.length?Math.round(mastered/questions.length*100):0}%</em></article><article><span>连续学习</span><strong>{streak}<small> 天</small></strong><em>累计约 {Math.round(history.length*3/6)/10} 小时</em></article></div><div className="stats-grid"><article className="chart-card"><span className="section-label">REVIEW ACTIVITY</span><h3>复习活动</h3><div className="bar-chart">{chart.map(item=><i key={item.key} className={item.value?'has-value':''} style={{height:`${Math.max(3,item.value/maxChart*100)}%`}}><b>{item.label}</b></i>)}</div></article><article className="mastery-card"><span className="section-label">CATEGORY MASTERY</span><h3>分类掌握度</h3>{category.slice(0,6).map(([name,value])=><div className="mastery-row" key={name}><span>{name}</span><i><em style={{width:`${value}%`}}/></i><b>{value}%</b></div>)}</article></div><div className="weak-card"><div><span className="section-label">NEEDS ATTENTION</span><h3>建议优先巩固</h3></div>{weak.slice(0,3).map((q,index)=><button key={q.id} onClick={()=>jump(q.id)}><i>{index+1}</i><span><b>{q.title}</b><small>{q.category} · 记忆强度 {progress[q.id]?.strength??q.strength}%</small></span><em>开始复习 →</em></button>)}</div></section>;
}

function AuthPanel({account,options,cloudStatus}:{account:Account;options:AuthOption[];cloudStatus:string}){
  const providerLabel={chatgpt:'ChatGPT',proxy:'自托管 SSO','cloudflare-access':'Cloudflare Access',development:'开发模式'}[account.provider||'chatgpt'];
  return <section className="auth-panel"><PageHeading label="ACCOUNT & SYNC" title="账号与同步" text="默认无需注册；登录后才开启跨设备云同步。开源部署者可按需接入一种身份方案。"><span className={`status-pill ${cloudStatus==='synced'?'online':''}`}>● {account.authenticated?`${providerLabel} · 已登录`:'无需账号 · 本机保存'}</span></PageHeading>{account.authenticated?<article className="signed-account"><div><span className="provider-mark">✓</span><span><b>{account.displayName}</b><small>{account.email} · {providerLabel}</small></span></div><p>学习记录先写入本机，再同步到当前账号的独立云空间。</p>{account.provider==='chatgpt'&&<a href="/signout-with-chatgpt?return_to=/">退出登录</a>}</article>:<div className="auth-option-grid">{options.map(option=><article key={option.id} className={option.available?'available':''}><span className="provider-mark">{option.id==='local'?'⌂':option.id==='github'?'GH':option.id==='google'?'G':option.id==='email'?'@':option.id==='chatgpt'?'AI':'SSO'}</span><h3>{option.label}</h3><p>{option.description}</p>{option.href&&option.available?<a href={option.href}>使用此方式 →</a>:<small>{option.available?'当前已可用':'部署者配置后可用'}</small>}</article>)}</div>}</section>;
}

function SettingsView({settings,setSettings,account,cloudStatus,aiMode,aiUsage,enableReminder,exportCalendar,exportData,importData,sharePack,resetAll}:{settings:Settings;setSettings:React.Dispatch<React.SetStateAction<Settings>>;account:Account;cloudStatus:string;aiMode:string;aiUsage:number;enableReminder:()=>void;exportCalendar:()=>void;exportData:()=>void;importData:(e:ChangeEvent<HTMLInputElement>)=>void;sharePack:()=>void;resetAll:()=>void}){
  return <section className="settings-view"><PageHeading label="PREFERENCES & DATA" title="学习与数据设置" text="学习数据始终先保存在本机；登录时自动同步，离线时仍可继续使用。"><span className={`status-pill ${cloudStatus==='synced'?'online':''}`}>● {account.authenticated?`${account.displayName} · 云同步`:'本机模式'}</span></PageHeading><div className="settings-grid expanded"><article><span className="step-number">01</span><h3>学习节奏</h3><label>每日目标 <b>{settings.dailyGoal} 题</b><input type="range" min="3" max="40" value={settings.dailyGoal} onChange={e=>setSettings(old=>({...old,dailyGoal:Number(e.target.value)}))}/></label><label>目标记忆率 <b>{Math.round(settings.targetRetention*100)}%</b><input type="range" min="80" max="97" value={settings.targetRetention*100} onChange={e=>setSettings(old=>({...old,targetRetention:Number(e.target.value)/100}))}/></label><small>记忆率越高，复习越频繁；90% 通常兼顾效率与牢固度。</small></article><article><span className="step-number">02</span><h3>提醒与补卡</h3><label>每天提醒时间 <input type="time" value={settings.reminderTime} onChange={e=>setSettings(old=>({...old,reminderTime:e.target.value}))}/></label><div className="data-actions"><button onClick={enableReminder}>{settings.notifications?'✓ 浏览器提醒已开启':'开启浏览器提醒'}</button><button onClick={exportCalendar}>加入系统日历</button></div><small>错过当天也不会丢失，未完成题目会自动滚入下一次任务。</small></article><article><span className="step-number">03</span><h3>AI 判题</h3><label>模型<select value={settings.model} onChange={e=>setSettings(old=>({...old,model:e.target.value}))}><option value="gpt-4.1-mini">gpt-4.1-mini · 省成本</option><option value="gpt-4.1">gpt-4.1 · 高质量</option><option value="gpt-4o-mini">gpt-4o-mini · 快速</option></select></label><label>每日 AI 上限 <b>{settings.dailyAiLimit} 次</b><input type="range" min="5" max="100" step="5" value={settings.dailyAiLimit} onChange={e=>setSettings(old=>({...old,dailyAiLimit:Number(e.target.value)}))}/></label><div className="mode-box"><i>◇</i><span><b>{aiMode==='ai'?'AI 已连接':'本地评估可用'}</b><small>今日 AI 请求 {aiUsage} / {settings.dailyAiLimit}</small></span></div></article><article><span className="step-number">04</span><h3>备份、迁移与分享</h3><p>完整备份含题库、进度、历史和设置；知识包只导出当前筛选的卡片。</p><div className="data-actions"><button onClick={exportData}>↓ 导出完整备份</button><label>↑ 导入 JSON / CSV / Markdown<input type="file" accept=".json,.csv,.md,.markdown" onChange={importData}/></label><button onClick={sharePack}>↗ 导出可分享知识包</button><button className="danger" onClick={resetAll}>恢复默认并清空</button></div></article></div><article className="principles-card"><div><span className="section-label">PRIVACY & RELIABILITY</span><h3>离线可学，联网自动同步</h3></div><p>匿名数据只留在当前浏览器；登录后同步到账号隔离的云数据。服务端每天自动保留一个版本，最多保存 20 个备份点。</p><div><span><b>FSRS</b> 间隔调度</span><span><b>D1</b> 账号同步</span><span><b>R2</b> 录音暂存</span></div></article></section>;
}

function Editor({draft,setDraft,save,close}:{draft:Draft;setDraft:React.Dispatch<React.SetStateAction<Draft>>;save:()=>void;close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)close();}}><section className="question-editor" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">KNOWLEDGE EDITOR</span><h2>{draft.id?'编辑知识点':'添加知识点'}</h2></div><button onClick={close} aria-label="关闭">×</button></div><div className="editor-grid"><label>分类<input value={draft.category} onChange={e=>setDraft(old=>({...old,category:e.target.value}))}/></label><label>难度<select value={draft.difficulty} onChange={e=>setDraft(old=>({...old,difficulty:Number(e.target.value) as 1|2|3}))}><option value="1">基础</option><option value="2">进阶</option><option value="3">困难</option></select></label><label className="full">题目<textarea value={draft.title} onChange={e=>setDraft(old=>({...old,title:e.target.value}))}/></label><label className="full">回答提示<input value={draft.hint} onChange={e=>setDraft(old=>({...old,hint:e.target.value}))}/></label><label>标签 <small>逗号分隔</small><input value={draft.tags} onChange={e=>setDraft(old=>({...old,tags:e.target.value}))} placeholder="MySQL，事务"/></label><label>前置知识 <small>题目 ID 或关键词</small><input value={draft.prerequisites} onChange={e=>setDraft(old=>({...old,prerequisites:e.target.value}))}/></label><label className="full">评分要点 <small>每行一个</small><textarea className="tall" value={draft.keyPoints} onChange={e=>setDraft(old=>({...old,keyPoints:e.target.value}))}/></label><label className="full">参考答案<textarea className="tall" value={draft.reference} onChange={e=>setDraft(old=>({...old,reference:e.target.value}))}/></label></div><div className="editor-actions"><button className="secondary-action" onClick={close}>取消</button><button className="primary-action" onClick={save}>保存知识点</button></div></section></div>}

function Generator({text,setText,cards,generate,add,loading,close}:{text:string;setText:(v:string)=>void;cards:Question[];generate:()=>void;add:()=>void;loading:boolean;close:()=>void}){return <div className="modal-backdrop"><section className="question-editor generator" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">AI CARD MAKER</span><h2>从材料生成记忆卡</h2></div><button onClick={close}>×</button></div><p className="modal-intro">粘贴笔记、文章或面试题解析，自动拆成问题、评分要点和参考答案。</p><textarea className="source-text" value={text} onChange={e=>setText(e.target.value)} placeholder="粘贴材料，支持最多 30,000 字……"/>{cards.length>0&&<div className="generated-list">{cards.map(card=><article key={card.id}><b>{card.title}</b><span>{card.category} · {card.keyPoints.length} 个评分点</span></article>)}</div>}<div className="editor-actions"><button className="secondary-action" onClick={close}>取消</button>{cards.length?<button className="primary-action" onClick={add}>加入题库（{cards.length}）</button>:<button className="primary-action" onClick={generate} disabled={loading}>{loading?'正在拆解材料…':'生成卡片'}</button>}</div></section></div>}

function mergeSnapshots(local:AppSnapshot,remote:AppSnapshot):AppSnapshot {const q=new Map(remote.questions.map(item=>[item.id,item]));local.questions.forEach(item=>q.set(item.id,item));const h=new Map(remote.history.map(item=>[item.id,item]));local.history.forEach(item=>h.set(item.id,item));return{...local,questions:[...q.values()],history:[...h.values()].sort((a,b)=>a.reviewedAt.localeCompare(b.reviewedAt)),progress:{...remote.progress,...local.progress},interviewReports:[...local.interviewReports,...remote.interviewReports.filter(item=>!local.interviewReports.some(old=>old.id===item.id))]};}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;link.click();URL.revokeObjectURL(url);}
