'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { DEFAULT_PROMPTS, InterviewRetrospective, LearningRoute, PromptKey, PromptTemplates, Question, RetentionState, Settings, WeeklyReport } from '../lib/model';

type PersonalApi={enabled:boolean;endpoint:string;apiKey:string;model:string};
const personalPayload=(value:PersonalApi)=>value.enabled?{endpoint:value.endpoint,apiKey:value.apiKey,model:value.model}:undefined;

export function LearningPacePanel({settings,setSettings,onReminder}:{settings:Settings;setSettings:React.Dispatch<React.SetStateAction<Settings>>;onReminder:()=>void}){
  return <section className="pace-panel"><div><span className="section-label">ADAPTIVE LEARNING</span><h3>目标、负担和完成日期</h3><p>开启后会根据近 7 天活跃度与答题分数，自动小幅缩减或增加当天任务；到期复习仍然优先。</p></div><label className="toggle-setting"><input type="checkbox" checked={settings.adaptiveDailyGoal} onChange={event=>setSettings(old=>({...old,adaptiveDailyGoal:event.target.checked}))}/><span><b>动态调整每日任务</b><small>{settings.adaptiveDailyGoal?'已开启':'使用固定上限'}</small></span></label><label>每周学习目标<select value={settings.weeklyGoal} onChange={event=>setSettings(old=>({...old,weeklyGoal:Number(event.target.value)}))}><option value="3">每周 3 天</option><option value="5">每周 5 天</option><option value="7">每天学习</option></select></label><label>希望完成日期<input type="date" value={settings.targetDate} onChange={event=>setSettings(old=>({...old,targetDate:event.target.value}))}/></label><div className="pace-actions"><button className="secondary-action" onClick={onReminder}>邮箱 / 企业微信提醒 →</button><a href="https://github.com/keii-2596/yihe-memory/raw/refs/heads/main/downloads/yihe-memory-android.apk">下载 Android App ↓</a></div></section>;
}

export function JdRouteModal({questions,prompt,personalAi,model,onCreated,onClose}:{questions:{id:string;title:string;category:string;tags?:string[];roleIds?:string[];levels?:string[];directionTags?:string[]}[];prompt:string;personalAi:PersonalApi;model:string;onCreated:(route:LearningRoute)=>void;onClose:()=>void}){
  const [description,setDescription]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  async function submit(){if(description.trim().length<20){setError('请粘贴更完整的岗位描述');return;}setLoading(true);setError('');try{const response=await fetch('/api/generate-route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description,questions,prompt,model,personalApi:personalPayload(personalAi)})});const data=await response.json() as {route?:LearningRoute;error?:string};if(!response.ok||!data.route)throw new Error(data.error||'生成失败');onCreated(data.route);}catch(value){setError(value instanceof Error?value.message:'生成失败');}finally{setLoading(false);}}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor expansion-modal" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">JD LEARNING ROUTE</span><h2>从岗位描述生成路线</h2></div><button onClick={onClose}>×</button></div><p className="modal-intro">粘贴招聘 JD，系统会识别岗位、级别和技术关键词，从现有题库中组合一条个人面试路线。JD 原文不会写入云同步。</p><textarea className="source-text" value={description} onChange={event=>setDescription(event.target.value)} placeholder="例如：负责 Java 微服务开发，熟悉 Spring Boot、MySQL、Redis、Kafka，有高并发系统设计经验……"/>{error&&<div className="ai-test-result error">{error}</div>}<div className="editor-actions"><button className="secondary-action" onClick={onClose}>取消</button><button className="primary-action" onClick={submit} disabled={loading}>{loading?'正在分析岗位…':'生成个人路线'}</button></div></section></div>;
}

export function WordbookEditorModal({route,questions,onSave,onDelete,onEditQuestion,onClose}:{route:LearningRoute;questions:Question[];onSave:(route:LearningRoute)=>void;onDelete?:()=>void;onEditQuestion:(question:Question)=>void;onClose:()=>void}){
  const [name,setName]=useState(route.name);const [description,setDescription]=useState(route.description);const [selected,setSelected]=useState<string[]>(route.questionIds||[]);const [search,setSearch]=useState('');const [category,setCategory]=useState('全部');
  const categories=['全部',...new Set(questions.map(item=>item.category))];const visible=questions.filter(item=>(category==='全部'||item.category===category)&&`${item.title}${item.category}${(item.tags||[]).join('')}`.toLowerCase().includes(search.toLowerCase()));
  function toggle(id:string){setSelected(ids=>ids.includes(id)?ids.filter(value=>value!==id):[...ids,id]);}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor wordbook-modal" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">CUSTOM WORD BOOK</span><h2>{route.id?'编辑自定义词书':'新建词书'}</h2></div><button onClick={onClose}>×</button></div><div className="editor-grid"><label className="full">词书名称<input value={name} onChange={event=>setName(event.target.value)} placeholder="例如：秋招 Java 冲刺"/></label><label className="full">说明<textarea value={description} onChange={event=>setDescription(event.target.value)} placeholder="这本词书的目标与范围"/></label></div><div className="wordbook-toolbar"><label>⌕<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="搜索知识点、分类或标签"/></label><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(value=><option key={value}>{value}</option>)}</select><b>已选 {selected.length} 个</b></div><div className="wordbook-question-list">{visible.map(question=><article key={question.id} className={selected.includes(question.id)?'selected':''}><label><input type="checkbox" checked={selected.includes(question.id)} onChange={()=>toggle(question.id)}/><span><b>{question.title}</b><small>{question.category} · {(question.tags||[]).join(' / ')||'未加标签'}</small></span></label><button onClick={()=>onEditQuestion(question)}>编辑内容</button></article>)}</div><div className="editor-actions wordbook-actions">{onDelete&&<button className="danger-link" onClick={onDelete}>删除这本词书</button>}<button className="secondary-action" onClick={onClose}>取消</button><button className="primary-action" disabled={!name.trim()||!selected.length} onClick={()=>onSave({...route,id:route.id||`book-${Date.now().toString(36)}`,name:name.trim(),description:description.trim()||'自定义面试知识词书',categories:[],questionIds:selected,source:route.source==='jd'||route.source==='interview'?route.source:'custom',createdAt:route.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()})}>保存词书（{selected.length}）</button></div></section></div>;
}

const promptMeta:{id:PromptKey;name:string;description:string;variables:string}[]=[
  {id:'evaluate',name:'AI 判题',description:'控制评分口径、反馈风格与关注维度。',variables:'{question} {answer} {keyPoints} {reference}'},
  {id:'followup',name:'面试追问',description:'决定追问的难度、风格和检验方向。',variables:'{question} {answer} {missedPoints}'},
  {id:'cardGeneration',name:'材料制卡',description:'控制材料拆题方式与题目粒度。',variables:'{material} {count}'},
  {id:'jdRoute',name:'JD 生成词书',description:'控制岗位关键词分析与选题偏好。',variables:'{jd}'},
  {id:'transcription',name:'录音转写',description:'帮助模型识别技术术语与对话结构。',variables:'无必填变量'},
  {id:'interviewReview',name:'面试复盘',description:'控制复盘维度、知识点提取和制题要求。',variables:'{role} {transcript}'},
];
export function PromptStudioModal({prompts,onSave,onClose}:{prompts:PromptTemplates;onSave:(prompts:PromptTemplates)=>void;onClose:()=>void}){
  const [draft,setDraft]=useState<PromptTemplates>({...DEFAULT_PROMPTS,...prompts});const [active,setActive]=useState<PromptKey>('evaluate');const meta=promptMeta.find(item=>item.id===active)!;
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor prompt-studio" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">PROMPT STUDIO</span><h2>LLM Prompt 工作台</h2></div><button onClick={onClose}>×</button></div><p className="modal-intro">每个 AI 场景都可以单独调整。变量会在发送前替换为当前内容；恢复默认不会影响题库和学习记录。</p><div className="prompt-layout"><nav>{promptMeta.map(item=><button key={item.id} className={active===item.id?'active':''} onClick={()=>setActive(item.id)}><b>{item.name}</b><small>{item.description}</small></button>)}</nav><div><div className="prompt-title"><span><b>{meta.name}</b><small>可用变量：{meta.variables}</small></span><button onClick={()=>setDraft(old=>({...old,[active]:DEFAULT_PROMPTS[active]}))}>恢复此项默认</button></div><textarea value={draft[active]} onChange={event=>setDraft(old=>({...old,[active]:event.target.value}))} spellCheck={false}/><p className="prompt-tip">系统仍会追加必要的 JSON 输出格式约束，以保证页面能读取结果。</p></div></div><div className="editor-actions"><button className="secondary-action" onClick={()=>setDraft(DEFAULT_PROMPTS)}>全部恢复默认</button><button className="primary-action" onClick={()=>onSave(draft)}>保存全部 Prompt</button></div></section></div>;
}

type ReviewResult={summary:string;overallFeedback:string;strengths:string[];weaknesses:string[];topics:{name:string;category:string;evidence:string;priority:'high'|'medium'|'low'}[];actionPlan:string[];cards:Omit<Question,'id'|'strength'>[];source:'ai'|'local';model?:string};
export function InterviewReviewView({settings,personalAi,reports,onSave}:{settings:Settings;personalAi:PersonalApi;reports:InterviewRetrospective[];onSave:(result:ReviewResult,role:string,transcript:string,createBook:boolean)=>void}){
  const [role,setRole]=useState('');const [transcript,setTranscript]=useState('');const [result,setResult]=useState<ReviewResult|null>(null);const [loading,setLoading]=useState<'idle'|'transcribing'|'analyzing'>('idle');const [error,setError]=useState('');
  async function upload(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;setError('');if(file.type.startsWith('audio/')||/\.(mp3|m4a|wav|webm|ogg)$/i.test(file.name)){setLoading('transcribing');try{const form=new FormData();form.set('audio',file);form.set('prompt',settings.prompts.transcription);const response=await fetch('/api/transcribe',{method:'POST',body:form});const data=await response.json() as {text?:string;error?:string};if(!response.ok||!data.text)throw new Error(data.error==='transcription_not_configured'?'站点尚未配置录音转写服务，可先上传或粘贴文字稿':data.error||'转写失败');setTranscript(data.text);}catch(value){setError(value instanceof Error?value.message:'转写失败');}finally{setLoading('idle');}return;}try{setTranscript(await file.text());}catch{setError('无法读取这个文字稿文件');}}
  async function analyze(){if(transcript.trim().length<50){setError('请提供更完整的面试文字稿（至少 50 字）');return;}setLoading('analyzing');setError('');try{const response=await fetch('/api/interview-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({transcript,role:role||'技术岗位',model:settings.model,prompt:settings.prompts.interviewReview,personalApi:personalPayload(personalAi)})});const data=await response.json() as ReviewResult&{error?:string};if(!response.ok)throw new Error(data.error||'复盘失败');setResult(data);}catch(value){setError(value instanceof Error?value.message:'复盘失败');}finally{setLoading('idle');}}
  return <section className="interview-review-view"><div className="page-heading"><div><span className="section-label">INTERVIEW RETROSPECTIVE</span><h2>面试复盘</h2><p>上传录音或文字稿，由 AI 提炼薄弱点并生成下一轮要背的题。</p></div><span className="status-pill">原始录音不保存</span></div><div className="review-workspace"><article className="review-input"><label>岗位 / 公司方向<input value={role} onChange={event=>setRole(event.target.value)} placeholder="例如：Java 后端 · 支付方向"/></label><label>面试文字稿<textarea value={transcript} onChange={event=>setTranscript(event.target.value)} placeholder="粘贴面试文字稿，或上传录音 / TXT / Markdown / SRT 文件……"/></label><div className="review-actions"><label className="secondary-action file-label">↑ 上传录音或文字稿<input type="file" accept="audio/*,.txt,.md,.markdown,.srt,.vtt" onChange={upload}/></label><button className="primary-action" onClick={analyze} disabled={loading!=='idle'}>{loading==='transcribing'?'正在转写录音…':loading==='analyzing'?'AI 正在复盘…':'开始 AI 复盘'}</button></div><small>文字稿会发送给你在设置中选择的 AI 服务；只同步复盘结论，不保存原始录音和完整文字稿。</small>{error&&<div className="ai-test-result error">{error}</div>}</article>{result?<article className="review-result"><span className="section-label">REVIEW RESULT · {result.source==='ai'?'AI':'本地提取'}</span><h3>{result.summary}</h3><p>{result.overallFeedback}</p><div className="review-columns"><div><b>做得不错</b>{result.strengths.map(value=><span key={value}>✓ {value}</span>)}</div><div><b>优先补强</b>{result.weaknesses.map(value=><span key={value}>↗ {value}</span>)}</div></div><div className="review-cards"><b>已生成 {result.cards.length} 道复习题</b>{result.cards.slice(0,5).map(card=><span key={card.title}>{card.category} · {card.title}</span>)}</div><div className="review-save-actions"><button className="secondary-action" onClick={()=>onSave(result,role||'技术岗位',transcript,false)}>只加入题库</button><button className="primary-action" onClick={()=>onSave(result,role||'技术岗位',transcript,true)}>加入题库并创建复盘词书</button></div></article>:<article className="review-history"><span className="section-label">PAST REVIEWS</span><h3>最近复盘</h3>{reports.length?reports.slice(0,5).map(report=><div key={report.id}><b>{report.role}</b><span>{report.createdAt.slice(0,10)} · {report.questionIds.length} 道题</span><p>{report.summary}</p></div>):<p>第一次复盘后，这里会保留结论、行动计划和生成的题目。</p>}</article>}</div></section>;
}

export function RetentionSection({report,calendar,completion,retention,onFreeze,onShare}:{report:WeeklyReport;calendar:{key:string;completed:number;due:number}[];completion:{remaining:number;days:number;date:string};retention:RetentionState;onFreeze:()=>void;onShare:()=>void}){
  const max=Math.max(1,...calendar.map(day=>day.completed));
  return <div className="retention-area"><article className="weekly-report"><div><span className="section-label">WEEKLY REPORT</span><h3>本周学习周报</h3><p>{report.summary}</p></div><div className="weekly-numbers"><span><b>{report.activeDays}</b>活跃天</span><span><b>{report.reviews}</b>次回忆</span><span><b>{report.newLearned}</b>个新知识</span><span><b>{report.averageScore}</b>平均分</span></div><footer><span>{report.start} 至 {report.end} · 较上周 {report.trend>=0?'+':''}{report.trend}%</span><button onClick={onShare}>隐私分享周报 →</button></footer></article><article className="learning-calendar"><div><span className="section-label">LEARNING CALENDAR</span><h3>最近 6 周</h3></div><div className="calendar-grid">{calendar.map(day=><i key={day.key} title={`${day.key} · 完成 ${day.completed} 次 · 到期 ${day.due} 个`} style={{opacity:.18+day.completed/max*.82}} className={day.completed?'done':''}/>)}</div><div className="calendar-legend"><span>少</span><i/><i/><i/><i/><span>多</span></div><p>{completion.remaining?`当前路线还有 ${completion.remaining} 个新知识，按目前上限约 ${completion.days} 天完成（预计 ${completion.date}）。`:'当前路线的新知识已经全部学过。'}</p></article><article className="streak-protection"><span className="section-label">STREAK PROTECTION</span><h3>学习连续性保护</h3><strong>{retention.streakFreezes}<small> 张补签卡</small></strong><p>昨天因临时事务中断时，可消耗一张补签卡保护连续学习；它不会伪造复习记录或提高记忆强度。</p><button onClick={onFreeze} disabled={!retention.streakFreezes}>为昨天补签</button></article></div>;
}

type Reminder={channel:string;destinationMasked:string;reminderTime:string;timezone:string;enabled:boolean;lastSentDate?:string|null};
export function ReminderModal({authenticated,defaultEmail,defaultTime,onClose}:{authenticated:boolean;defaultEmail?:string;defaultTime:string;onClose:()=>void}){
  const [channel,setChannel]=useState<'email'|'wechat'>('email');const [destination,setDestination]=useState(defaultEmail||'');const [time,setTime]=useState(defaultTime);const [reminders,setReminders]=useState<Reminder[]>([]);const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!authenticated)return;fetch('/api/reminders').then(async response=>{const data=await response.json() as {reminders?:Reminder[]};if(response.ok)setReminders(data.reminders||[]);}).catch(()=>undefined);},[authenticated]);
  async function save(){if(!authenticated){setMessage('请先登录，再配置跨设备提醒');return;}setLoading(true);setMessage('');try{const response=await fetch('/api/reminders',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,destination,reminderTime:time,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,enabled:true})});const data=await response.json() as {reminder?:Reminder;error?:string};if(!response.ok||!data.reminder)throw new Error(data.error||'保存失败');setReminders(items=>[...items.filter(item=>item.channel!==channel),data.reminder!]);setDestination('');setMessage('提醒方式已保存');}catch(value){setMessage(value instanceof Error?value.message:'保存失败');}finally{setLoading(false);}}
  async function remove(item:Reminder){const response=await fetch(`/api/reminders?channel=${encodeURIComponent(item.channel)}`,{method:'DELETE'});if(response.ok)setReminders(items=>items.filter(row=>row.channel!==item.channel));}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor expansion-modal" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">REMINDER CENTER</span><h2>跨设备学习提醒</h2></div><button onClick={onClose}>×</button></div><p className="modal-intro">浏览器提醒继续保留；登录后还可配置邮箱或企业微信群机器人。普通个人微信暂不提供可靠的官方机器人接口。</p>{!authenticated&&<div className="ai-test-result error">需要先登录 ChatGPT 或自托管账号，提醒地址才会安全保存在你的云空间。</div>}<div className="reminder-existing">{reminders.map(item=><article key={item.channel}><span><b>{item.channel==='email'?'邮箱':'企业微信群'}</b><small>{item.destinationMasked} · 每天 {item.reminderTime}</small></span><button onClick={()=>remove(item)}>删除</button></article>)}</div><div className="provider-grid reminder-channels"><button className={channel==='email'?'selected':''} onClick={()=>setChannel('email')}><b>邮箱提醒</b><small>由站点定时发送</small></button><button className={channel==='wechat'?'selected':''} onClick={()=>setChannel('wechat')}><b>企业微信群</b><small>群机器人 Webhook</small></button></div><div className="editor-grid"><label className="full">{channel==='email'?'接收邮箱':'企业微信群机器人 Webhook'}<input type={channel==='email'?'email':'url'} value={destination} onChange={event=>setDestination(event.target.value)} placeholder={channel==='email'?'name@example.com':'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=…'}/></label><label className="full">提醒时间<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div>{message&&<div className={`ai-test-result ${message.includes('已保存')?'success':'error'}`}>{message}</div>}<div className="editor-actions"><button className="secondary-action" onClick={onClose}>完成</button><button className="primary-action" onClick={save} disabled={loading||!authenticated}>{loading?'保存中…':'保存提醒方式'}</button></div></section></div>;
}

export function MaterialImportTools({onText,onError}:{onText:(text:string,label:string)=>void;onError:(message:string)=>void}){
  const [url,setUrl]=useState('');const [loading,setLoading]=useState(false);
  async function importUrl(){if(!url.trim()){onError('请先输入网页地址');return;}setLoading(true);try{const response=await fetch('/api/import-source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await response.json() as {text?:string;title?:string;error?:string};if(!response.ok||!data.text)throw new Error(data.error||'网页读取失败');onText(data.text,data.title||'网页材料');setUrl('');}catch(value){onError(value instanceof Error?value.message:'网页读取失败');}finally{setLoading(false);}}
  async function importPdf(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;setLoading(true);try{const form=new FormData();form.set('file',file);const response=await fetch('/api/import-document',{method:'POST',body:form});const data=await response.json() as {text?:string;title?:string;error?:string};if(!response.ok||!data.text)throw new Error(data.error||'PDF 解析失败');onText(data.text,data.title||file.name);}catch(value){onError(value instanceof Error?value.message:'PDF 解析失败');}finally{setLoading(false);}}
  return <div className="material-tools"><label><span>网页地址</span><div><input type="url" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://…"/><button onClick={importUrl} disabled={loading}>{loading?'读取中…':'读取网页'}</button></div></label><label className="material-file">上传 PDF / 笔记文件<input type="file" accept="application/pdf,.pdf" onChange={importPdf}/></label></div>;
}
