'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { LearningRoute, RetentionState, Settings, WeeklyReport } from '../lib/model';

export function LearningPacePanel({settings,setSettings,onReminder}:{settings:Settings;setSettings:React.Dispatch<React.SetStateAction<Settings>>;onReminder:()=>void}){
  return <section className="pace-panel"><div><span className="section-label">ADAPTIVE LEARNING</span><h3>目标、负担和完成日期</h3><p>开启后会根据近 7 天活跃度与答题分数，自动小幅缩减或增加当天任务；到期复习仍然优先。</p></div><label className="toggle-setting"><input type="checkbox" checked={settings.adaptiveDailyGoal} onChange={event=>setSettings(old=>({...old,adaptiveDailyGoal:event.target.checked}))}/><span><b>动态调整每日任务</b><small>{settings.adaptiveDailyGoal?'已开启':'使用固定上限'}</small></span></label><label>每周学习目标<select value={settings.weeklyGoal} onChange={event=>setSettings(old=>({...old,weeklyGoal:Number(event.target.value)}))}><option value="3">每周 3 天</option><option value="5">每周 5 天</option><option value="7">每天学习</option></select></label><label>希望完成日期<input type="date" value={settings.targetDate} onChange={event=>setSettings(old=>({...old,targetDate:event.target.value}))}/></label><div className="pace-actions"><button className="secondary-action" onClick={onReminder}>邮箱 / 企业微信提醒 →</button><a href="https://github.com/keii-2596/yihe-memory/releases/latest/download/yihe-memory-android.apk">下载 Android App ↓</a></div></section>;
}

export function JdRouteModal({questions,onCreated,onClose}:{questions:{id:string;title:string;category:string;tags?:string[];roleIds?:string[];levels?:string[];directionTags?:string[]}[];onCreated:(route:LearningRoute)=>void;onClose:()=>void}){
  const [description,setDescription]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('');
  async function submit(){if(description.trim().length<20){setError('请粘贴更完整的岗位描述');return;}setLoading(true);setError('');try{const response=await fetch('/api/generate-route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({description,questions})});const data=await response.json() as {route?:LearningRoute;error?:string};if(!response.ok||!data.route)throw new Error(data.error||'生成失败');onCreated(data.route);}catch(value){setError(value instanceof Error?value.message:'生成失败');}finally{setLoading(false);}}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor expansion-modal" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">JD LEARNING ROUTE</span><h2>从岗位描述生成路线</h2></div><button onClick={onClose}>×</button></div><p className="modal-intro">粘贴招聘 JD，系统会识别岗位、级别和技术关键词，从现有题库中组合一条个人面试路线。JD 原文不会写入云同步。</p><textarea className="source-text" value={description} onChange={event=>setDescription(event.target.value)} placeholder="例如：负责 Java 微服务开发，熟悉 Spring Boot、MySQL、Redis、Kafka，有高并发系统设计经验……"/>{error&&<div className="ai-test-result error">{error}</div>}<div className="editor-actions"><button className="secondary-action" onClick={onClose}>取消</button><button className="primary-action" onClick={submit} disabled={loading}>{loading?'正在分析岗位…':'生成个人路线'}</button></div></section></div>;
}

export function RetentionSection({report,calendar,completion,retention,onFreeze,onShare}:{report:WeeklyReport;calendar:{key:string;completed:number;due:number}[];completion:{remaining:number;days:number;date:string};retention:RetentionState;onFreeze:()=>void;onShare:()=>void}){
  const max=Math.max(1,...calendar.map(day=>day.completed));
  return <div className="retention-area"><article className="weekly-report"><div><span className="section-label">WEEKLY REPORT</span><h3>本周学习周报</h3><p>{report.summary}</p></div><div className="weekly-numbers"><span><b>{report.activeDays}</b>活跃天</span><span><b>{report.reviews}</b>次回忆</span><span><b>{report.newLearned}</b>个新知识</span><span><b>{report.averageScore}</b>平均分</span></div><footer><span>{report.start} 至 {report.end} · 较上周 {report.trend>=0?'+':''}{report.trend}%</span><button onClick={onShare}>隐私分享周报 →</button></footer></article><article className="learning-calendar"><div><span className="section-label">LEARNING CALENDAR</span><h3>最近 6 周</h3></div><div className="calendar-grid">{calendar.map(day=><i key={day.key} title={`${day.key} · 完成 ${day.completed} 次 · 到期 ${day.due} 个`} style={{opacity:.18+day.completed/max*.82}} className={day.completed?'done':''}/>)}</div><div className="calendar-legend"><span>少</span><i/><i/><i/><i/><span>多</span></div><p>{completion.remaining?`当前路线还有 ${completion.remaining} 个新知识，按目前上限约 ${completion.days} 天完成（预计 ${completion.date}）。`:'当前路线的新知识已经全部学过。'}</p></article><article className="streak-protection"><span className="section-label">STREAK PROTECTION</span><h3>学习连续性保护</h3><strong>{retention.streakFreezes}<small> 张补签卡</small></strong><p>昨天因临时事务中断时，可消耗一张补签卡保护连续学习；它不会伪造复习记录或提高记忆强度。</p><button onClick={onFreeze} disabled={!retention.streakFreezes}>为昨天补签</button></article></div>;
}

type Reminder={channel:string;destinationMasked:string;reminderTime:string;timezone:string;enabled:boolean;lastSentDate?:string|null};
export function ReminderModal({authenticated,defaultEmail,defaultTime,onClose}:{authenticated:boolean;defaultEmail?:string;defaultTime:string;onClose:()=>void}){
  const [channel,setChannel]=useState<'email'|'wechat'>('email');const [destination,setDestination]=useState(defaultEmail||'');const [time,setTime]=useState(defaultTime);const [reminders,setReminders]=useState<Reminder[]>([]);const [message,setMessage]=useState('');const [loading,setLoading]=useState(false);
  useEffect(()=>{if(!authenticated)return;fetch('/api/reminders').then(async response=>{const data=await response.json() as {reminders?:Reminder[]};if(response.ok)setReminders(data.reminders||[]);}).catch(()=>undefined);},[authenticated]);
  async function save(){if(!authenticated){setMessage('请先登录，再配置跨设备提醒');return;}setLoading(true);setMessage('');try{const response=await fetch('/api/reminders',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({channel,destination,reminderTime:time,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,enabled:true})});const data=await response.json() as {reminder?:Reminder;error?:string};if(!response.ok||!data.reminder)throw new Error(data.error||'保存失败');setReminders(items=>[...items.filter(item=>item.channel!==channel),data.reminder!]);setDestination('');setMessage('提醒方式已保存');}catch(value){setMessage(value instanceof Error?value.message:'保存失败');}finally{setLoading(false);}}
  async function remove(item:Reminder){const response=await fetch(`/api/reminders?channel=${encodeURIComponent(item.channel)}`,{method:'DELETE'});if(response.ok)setReminders(items=>items.filter(row=>row.channel!==item.channel));}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose();}}><section className="question-editor expansion-modal" role="dialog" aria-modal="true"><div className="editor-head"><div><span className="section-label">REMINDER CENTER</span><h2>跨设备学习提醒</h2></div><button onClick={onClose}>×</button></div><p className="modal-intro">浏览器提醒继续保留；登录后还可配置邮箱或企业微信群机器人。普通个人微信暂不提供可靠的官方机器人接口。</p>{!authenticated&&<div className="ai-test-result error">需要先登录 ChatGPT 或自托管账号，提醒地址才会安全保存在你的云空间。</div>}<div className="reminder-existing">{reminders.map(item=><article key={item.channel}><span><b>{item.channel==='email'?'邮箱':'企业微信群'}</b><small>{item.destinationMasked} · 每天 {item.reminderTime}</small></span><button onClick={()=>remove(item)}>删除</button></article>)}</div><div className="provider-grid reminder-channels"><button className={channel==='email'?'selected':''} onClick={()=>setChannel('email')}><b>邮箱提醒</b><small>由站点定时发送</small></button><button className={channel==='wechat'?'selected':''} onClick={()=>setChannel('wechat')}><b>企业微信群</b><small>群机器人 Webhook</small></button></div><div className="editor-grid"><label className="full">{channel==='email'?'接收邮箱':'企业微信群机器人 Webhook'}<input type={channel==='email'?'email':'url'} value={destination} onChange={event=>setDestination(event.target.value)} placeholder={channel==='email'?'name@example.com':'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=…'}/></label><label className="full">提醒时间<input type="time" value={time} onChange={event=>setTime(event.target.value)}/></label></div>{message&&<div className={`ai-test-result ${message.includes('已保存')?'success':'error'}`}>{message}</div>}<div className="editor-actions"><button className="secondary-action" onClick={onClose}>完成</button><button className="primary-action" onClick={save} disabled={loading||!authenticated}>{loading?'保存中…':'保存提醒方式'}</button></div></section></div>;
}

export function MaterialImportTools({onText,onError}:{onText:(text:string,label:string)=>void;onError:(message:string)=>void}){
  const [url,setUrl]=useState('');const [loading,setLoading]=useState(false);
  async function importUrl(){if(!url.trim()){onError('请先输入网页地址');return;}setLoading(true);try{const response=await fetch('/api/import-source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url})});const data=await response.json() as {text?:string;title?:string;error?:string};if(!response.ok||!data.text)throw new Error(data.error||'网页读取失败');onText(data.text,data.title||'网页材料');setUrl('');}catch(value){onError(value instanceof Error?value.message:'网页读取失败');}finally{setLoading(false);}}
  async function importPdf(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];event.target.value='';if(!file)return;setLoading(true);try{const form=new FormData();form.set('file',file);const response=await fetch('/api/import-document',{method:'POST',body:form});const data=await response.json() as {text?:string;title?:string;error?:string};if(!response.ok||!data.text)throw new Error(data.error||'PDF 解析失败');onText(data.text,data.title||file.name);}catch(value){onError(value instanceof Error?value.message:'PDF 解析失败');}finally{setLoading(false);}}
  return <div className="material-tools"><label><span>网页地址</span><div><input type="url" value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://…"/><button onClick={importUrl} disabled={loading}>{loading?'读取中…':'读取网页'}</button></div></label><label className="material-file">上传 PDF / 笔记文件<input type="file" accept="application/pdf,.pdf" onChange={importPdf}/></label></div>;
}
